version: "3"
networks:
  application:
    driver: bridge
services:
  app:
    container_name: app_tier
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=default
      - AWS_REGION=your-region
    depends_on:
      - db
    networks:
      - application
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        composer install
        php artisan migrate
        php artisan serve --host=0.0.0.0 --port=8000
  db:
    container_name: db_tier
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./storage/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=intelli_c3_fmi
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
